export const articleListData = [
  {
    title: 'Sample Title',
    author: 'John Doe',
    category: 'General',
    tags: 'politics',
    date: '8/12/2021',
  },
  {
    title: 'Sample Title',
    author: 'John Doe',
    category: 'General',
    tags: 'politics',
    date: '8/12/2021',
  },
  {
    title: 'Sample Title',
    author: 'John Doe',
    category: 'General',
    tags: 'politics',
    date: '8/12/2021',
  },
  {
    title: 'Sample Title',
    author: 'John Doe',
    category: 'General',
    tags: 'politics',
    date: '8/12/2021',
  },
  {
    title: 'Sample Title',
    author: 'John Doe',
    category: 'General',
    tags: 'politics',
    date: '8/12/2021',
  },
  {
    title: 'Sample Title',
    author: 'John Doe',
    category: 'General',
    tags: 'politics',
    date: '8/12/2021',
  },
  {
    title: 'Sample Title',
    author: 'John Doe',
    category: 'General',
    tags: 'politics',
    date: '8/12/2021',
  },
  {
    title: 'Sample Title',
    author: 'John Doe',
    category: 'General',
    tags: 'politics',
    date: '8/12/2021',
  },
  {
    title: 'Sample Title',
    author: 'John Doe',
    category: 'General',
    tags: 'politics',
    date: '8/12/2021',
  },
  {
    title: 'Sample Title',
    author: 'John Doe',
    category: 'General',
    tags: 'politics',
    date: '8/12/2021',
  },
  {
    title: 'Sample Title',
    author: 'John Doe',
    category: 'General',
    tags: 'politics',
    date: '8/12/2021',
  },
];
