export const articleListData = [
  {
    id: '1',
    title: 'Sample Title',
    author: 'John Doe',
    category: 'General',
    tags: 'politics',
    date: '8/12/2021',
  },
  {
    id: '2',
    title: 'Sample Title',
    author: 'John Doe',
    category: 'General',
    tags: 'politics',
    date: '8/12/2021',
  },
  {
    id: '3',
    title: 'Sample Title',
    author: 'John Doe',
    category: 'General',
    tags: 'politics',
    date: '8/12/2021',
  },
  {
    id: '4',
    title: 'Sample Title',
    author: 'John Doe',
    category: 'General',
    tags: 'politics',
    date: '8/12/2021',
  },
  {
    id: '5',
    title: 'Sample Title',
    author: 'John Doe',
    category: 'General',
    tags: 'politics',
    date: '8/12/2021',
  },
  {
    id: '6',
    title: 'Sample Title',
    author: 'John Doe',
    category: 'General',
    tags: 'politics',
    date: '8/12/2021',
  },
  {
    id: '7',
    title: 'Sample Title',
    author: 'John Doe',
    category: 'General',
    tags: 'politics',
    date: '8/12/2021',
  },
  {
    id: '8',
    title: 'Sample Title',
    author: 'John Doe',
    category: 'General',
    tags: 'politics',
    date: '8/12/2021',
  },
];
